### ISSUE TITLE
Plugin Loader

### ISSUE THREAD

**Issue by luxass** [zotera/zotera#1]
Currently we started on a plugin loader, but it's not quite ready yet.

I think the plugin loader should work something like this:

We can use plugins directly or add options to them.
```yaml
plugins:
  - zotera-test-1 # This plugin does not have any options/are using default
  - zotera-test-2:
      placeholder: '@' # This is a settings for the specific plugin.
```

Plugin Loader should unzip the .zop file and store it inside config pluginsDir option to so we can load it.
